from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from backend.core.config import settings


# Base class for all ORM models
# Every model in backend/core/models.py inherits from this Base.
# init_db() uses Base.metadata.create_all() to create all tables.
class Base(DeclarativeBase):
    pass


# Async engine
# echo=False in production, set to True temporarily if needed to debug SQL statements being generated by SQLAlchemy.
engine = create_async_engine(
    settings.database_url,
    echo=False,
    connect_args={"check_same_thread": False},
)


# Session factory
# expire_on_commit=False means ORM objects remain usable after a commit
# without needing to be refreshed from the DB. Important for async code
# where lazy loading is not available.
AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


# FastAPI dependency
# Usage in any endpoint (that needs a database):
# async def my_endpoint(db: AsyncSession = Depends(get_db)):
# Yields a session, commits on success, rolls back on exception,
# always closes the session when the request is done.
async def get_db():
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# Startup initialiser
# Called once at app startup.
# Creates all tables defined in backend/core/models.py if they do not
# already exist. Safe to call on every startup — will not drop existing data.
async def init_db():
    # Import here to avoid circular imports.
    # models.py imports Base from this file; this function imports models
    # so that Base.metadata is populated before create_all runs.
    from backend.core import models  # noqa: F401

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)